name: デプロイ(Linux)
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  build_for_linux:
    name: Linux用ビルド
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter Develop dependencies
        run:  sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel:  'stable'
          cache:  true

      - name: Cache pubspec dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.FLUTTER_HOME }}/.pub-cache
            **/.packages
            **/.flutter-plugins
            **/.flutter-plugin-dependencies
            **/.dart_tool/package_config.json
          key:  build-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: build-pubspec-

      - name: Convert Icon Image
        run:  |
          sudo apt install -y imagemagick
          convert assets/images/icon.png 256x256 assets/images/miria.png
          rm assets/images/icon_adaptive.png

      - name: Install Flutter Build Tools for Linux
        run:  sudo apt install -y libsecret-1-dev

      - name: Flutter pub get
        run:  flutter pub get

      - name: Get Version
        run:  echo "VERSION=$(flutter pub run cider version)" >> $GITHUB_ENV

      - name: Flutter Build
        run:  flutter build linux --release

      - name: Setup Packaging AppImage
        run:  |
          sudo apt install -y locate libfuse2
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          sudo mv appimagetool /usr/local/bin/
          flutter pub global activate flutter_distributor

      - name: Packaging AppImage and deb
        run:  |
          flutter_distributor package --platform linux --targets appimage,deb --skip-clean
          mv ./dist/$BUMP_VERSION/miria-$BUMP_VERSION-linux.AppImage miria-$BUMP_VERSION-amd64.AppImage
          mv ./dist/$BUMP_VERSION/miria-$BUMP_VERSION-linux.deb miria-$BUMP_VERSION-amd64.deb

      - name: Upload AppImage and deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:  gh release upload v$VERSION miria-$BUMP_VERSION-amd64.AppImage miria-$BUMP_VERSION-amd64.deb

      - name: Compress App to tar.gz
        run:  |
          cd build/linux/x64/release/bundle
          tar -czaf miria-$VERSION-x86_64.tar.gz *

      - name: Upload tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:  gh release upload v$VERSION ./build/linux/x64/release/bundle/miria-$VERSION-x86_64.tar.gz

      - name: Remove artifact.tar.gz
        run:  rm build/linux/x64/release/bundle/miria-$VERSION-x86_64.tar.gz
