
name: デプロイ(snap)
on:
  workflow_dispatch:
  push:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: ビルド（Snap）
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Flutter Develop dependencies
        run:  sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Cache pubspec dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.FLUTTER_HOME }}/.pub-cache
            **/.packages
            **/.flutter-plugins
            **/.flutter-plugin-dependencies
            **/.dart_tool/package_config.json
          key:  build-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: build-pubspec-

      - name: Install Flutter Build Tools for Linux
        run:  sudo apt install -y libsecret-1-dev libmpv-dev

      - name: Flutter Build
        run:  |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter build linux --release

      - name: Get Version
        run:  echo "VERSION=$(flutter pub run cider version)" >> $GITHUB_ENV

      - name: Build Snap
        id: snapcraft
        uses: snapcore/action-build@v1

      - name: Upload snap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v$VERSION ${{ steps.snapcraft.outputs.snap }}
      # https://gihyo.jp/admin/serial/01/ubuntu-recipe/0660#sec3 : Snapパッケージアップロードまでの流れ
      # https://github.com/snapcore/action-publish : Snap ActionのREADME.md
      # Snap Storeでパッケージ名"miria"を予約（$ snapcraft register miria）後、"SNAPCRAFT_STORE_CREDENTIALS"を登録し、
      # 以下をコメントアウトを解除することでSnap Storeへアップロードすることが可能です。
      # 通常、SnapファイルをそのままStore外で公開することはありません。
      #
      #- name: Upload Snap Store
      #  uses: snapcore/action-publish@v1
      #  env:
      #    SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      #  with:
      #    snap: ${{ steps.snapcraft.outputs.snap }}
      #    release: stable

