#!/bin/sh
appimagepath="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH=${appimagepath}/lib:${appimagepath}
export PATH=${appimagepath}/bin:${PATH}
export XDG_DATA_DIRS=${appimagepath}/share:${XDG_DATA_DIRS}
exec "${appimagepath}/miria"